package net.anglewyrm.pixies;


import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
//import org.apache.logging.log4j.Logger;
import net.minecraft.block.Block;
import net.minecraft.item.Item;

// Storage for all hard-coded constant values
public class Constants {
	
	public static final String modid = "Pixies";
	public static final String name = modid;
	public static final String version = "pre-Alpha";
	
	public static ModMetadata metadata;
	public static void setMetadata(FMLPreInitializationEvent event){
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.modId = modid;
		metadata.name = modid;
		metadata.version = version;
		metadata.description = "[Description String]";	
		metadata.credits = "[credits]";
		metadata.logoFile = "assets/logo.png";		
	}
	
	public Constants() { /* NOP */ }
}
